import jsPDF from "jspdf";
import { SavedQuestion } from "../types";

/**
 * Downloads a single note as a beautifully styled PDF file.
 */
export function downloadSingleNotePDF(note: SavedQuestion): void {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 18;
    const contentWidth = pageWidth - margin * 2;

    // Header Background Accent
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, pageWidth, 32, "F");

    // Decorative emerald bar
    doc.setFillColor(16, 185, 129); // emerald-500
    doc.rect(0, 32, pageWidth, 3, "F");

    // Header Title
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("WB STUDY AI • REVISION NOTE", margin, 14);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(203, 213, 225); // slate-300
    doc.text("West Bengal Board (WBBSE & WBCHSE) Offline Study Material", margin, 22);

    // Note Meta Badges (Subject, Class, Date)
    let cursorY = 46;

    // Badge container
    doc.setFillColor(241, 245, 249); // slate-100
    doc.roundedRect(margin, cursorY, contentWidth, 20, 3, 3, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`Subject: ${note.subject}`, margin + 5, cursorY + 8);
    doc.text(`Class: ${note.classLevel}`, margin + 5, cursorY + 15);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Saved Date: ${note.date}`, pageWidth - margin - 50, cursorY + 8);
    doc.text(`Format: Offline Revision PDF`, pageWidth - margin - 50, cursorY + 15);

    cursorY += 30;

    // Note Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59); // slate-800
    const splitTitle = doc.splitTextToSize(note.title, contentWidth);
    doc.text(splitTitle, margin, cursorY);
    cursorY += splitTitle.length * 6 + 4;

    // Divider
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setLineWidth(0.5);
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 8;

    // Content
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(51, 65, 85); // slate-700

    const splitContent = doc.splitTextToSize(note.content, contentWidth);

    for (let i = 0; i < splitContent.length; i++) {
      if (cursorY > pageHeight - 25) {
        doc.addPage();
        cursorY = 20;

        // Subtle header on subsequent pages
        doc.setFont("helvetica", "italic");
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`WB Study AI - ${note.title} (Class ${note.classLevel})`, margin, 12);
        doc.line(margin, 14, pageWidth - margin, 14);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10.5);
        doc.setTextColor(51, 65, 85);
      }
      doc.text(splitContent[i], margin, cursorY);
      cursorY += 5.5;
    }

    // Footer on the last page
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by WB Study AI • For Offline Exam Revision", margin, pageHeight - 10);
    doc.text(`Page 1 of ${doc.getNumberOfPages()}`, pageWidth - margin - 20, pageHeight - 10);

    const safeFilename = note.title
      .replace(/[^a-zA-Z0-9_-]/g, "_")
      .substring(0, 30);
    doc.save(`Note_${safeFilename}_Class${note.classLevel}.pdf`);
  } catch (err) {
    console.error("Failed to generate single note PDF with jsPDF:", err);
    // Fallback to styled HTML print / PDF window
    generatePrintablePDFHTML([note], `Class ${note.classLevel} - ${note.title}`);
  }
}

/**
 * Downloads all saved notes as a single comprehensive PDF booklet.
 */
export function downloadAllNotesPDF(notes: SavedQuestion[], currentClass: string): void {
  if (!notes || notes.length === 0) return;

  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 18;
    const contentWidth = pageWidth - margin * 2;

    // Cover / Header Banner
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setFillColor(16, 185, 129); // emerald-500
    doc.rect(0, 40, pageWidth, 3, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("WB STUDY AI • REVISION COMPENDIUM", margin, 18);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(203, 213, 225);
    doc.text(`West Bengal Board • Class ${currentClass} Offline Saved Study Notes (${notes.length} Topics)`, margin, 27);
    doc.text(`Export Date: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`, margin, 34);

    let cursorY = 55;

    notes.forEach((note, index) => {
      // Check if we need a new page for note header
      if (cursorY > pageHeight - 40) {
        doc.addPage();
        cursorY = 25;
      }

      // Note Card Banner
      doc.setFillColor(248, 250, 252); // slate-50
      doc.setDrawColor(203, 213, 225); // slate-300
      doc.roundedRect(margin, cursorY, contentWidth, 14, 2, 2, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text(`#${index + 1} • ${note.subject} (Class ${note.classLevel})`, margin + 4, cursorY + 6);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(`Date: ${note.date}`, pageWidth - margin - 35, cursorY + 6);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(3, 105, 161); // sky-700
      const splitTitle = doc.splitTextToSize(note.title, contentWidth - 8);
      doc.text(splitTitle, margin + 4, cursorY + 11);

      cursorY += 18;

      // Note Content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(51, 65, 85);

      const splitContent = doc.splitTextToSize(note.content, contentWidth - 4);

      for (let i = 0; i < splitContent.length; i++) {
        if (cursorY > pageHeight - 20) {
          doc.addPage();
          cursorY = 22;

          // Header on new pages
          doc.setFont("helvetica", "italic");
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.text(`WB Study AI • Class ${currentClass} Study Notes Booklet`, margin, 12);
          doc.line(margin, 14, pageWidth - margin, 14);

          doc.setFont("helvetica", "normal");
          doc.setFontSize(9.5);
          doc.setTextColor(51, 65, 85);
        }
        doc.text(splitContent[i], margin + 2, cursorY);
        cursorY += 5;
      }

      cursorY += 8; // Spacing between notes
    });

    // Add page numbers
    const totalPages = doc.getNumberOfPages();
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text("WB Study AI • West Bengal Board Offline Revision", margin, pageHeight - 8);
      doc.text(`Page ${p} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 8);
    }

    doc.save(`WB_Study_Notes_Class_${currentClass}_All.pdf`);
  } catch (err) {
    console.error("Failed to generate multi-note PDF with jsPDF:", err);
    generatePrintablePDFHTML(notes, `Class ${currentClass} - Complete Notes Compendium`);
  }
}

/**
 * Fallback & printable styled HTML document renderer (supports Bengali/Indic Unicode glyphs natively in browser print).
 */
export function generatePrintablePDFHTML(notes: SavedQuestion[], docTitle: string): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to open the PDF printable notes document.");
    return;
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>${docTitle} - WB Study AI</title>
      <style>
        @page {
          size: A4;
          margin: 15mm 15mm 20mm 15mm;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans Bengali", sans-serif;
          color: #1e293b;
          line-height: 1.6;
          margin: 0;
          padding: 20px;
          background: #ffffff;
        }
        .header {
          background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%);
          color: #ffffff;
          padding: 20px 24px;
          border-radius: 12px;
          margin-bottom: 24px;
          border-bottom: 4px solid #10b981;
        }
        .header h1 {
          margin: 0 0 4px 0;
          font-size: 22px;
          font-weight: 800;
          letter-spacing: -0.5px;
        }
        .header p {
          margin: 0;
          font-size: 13px;
          color: #cbd5e1;
        }
        .note-card {
          border: 1px solid #e2e8f0;
          border-radius: 10px;
          padding: 16px 20px;
          margin-bottom: 20px;
          page-break-inside: avoid;
          background: #f8fafc;
        }
        .note-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-bottom: 1px solid #e2e8f0;
          padding-bottom: 8px;
          margin-bottom: 10px;
        }
        .subject-badge {
          background: #e0e7ff;
          color: #3730a3;
          font-size: 11px;
          font-weight: 700;
          padding: 3px 8px;
          border-radius: 6px;
        }
        .note-date {
          font-size: 11px;
          color: #64748b;
        }
        .note-title {
          font-size: 15px;
          font-weight: 700;
          color: #0f172a;
          margin: 0 0 10px 0;
        }
        .note-content {
          font-size: 13px;
          color: #334155;
          white-space: pre-wrap;
        }
        .footer {
          margin-top: 30px;
          text-align: center;
          font-size: 11px;
          color: #94a3b8;
          border-top: 1px solid #e2e8f0;
          padding-top: 10px;
        }
        @media print {
          body { padding: 0; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="no-print" style="margin-bottom: 16px; display: flex; gap: 10px; justify-content: flex-end;">
        <button onclick="window.print()" style="background: #10b981; color: white; border: none; padding: 8px 16px; border-radius: 6px; font-weight: bold; cursor: pointer;">
          🖨️ Print / Save as PDF
        </button>
        <button onclick="window.close()" style="background: #e2e8f0; color: #334155; border: none; padding: 8px 16px; border-radius: 6px; font-weight: bold; cursor: pointer;">
          Close
        </button>
      </div>

      <div class="header">
        <h1>WB STUDY AI • REVISION BOOKLET</h1>
        <p>West Bengal Board (WBBSE & WBCHSE) • ${docTitle}</p>
      </div>

      ${notes
        .map(
          (n, i) => `
        <div class="note-card">
          <div class="note-header">
            <span class="subject-badge">${n.subject} • Class ${n.classLevel}</span>
            <span class="note-date">${n.date}</span>
          </div>
          <h2 class="note-title">#${i + 1}. ${n.title}</h2>
          <div class="note-content">${n.content}</div>
        </div>
      `
        )
        .join("")}

      <div class="footer">
        Generated by WB Study AI • Offline Learning Platform for West Bengal Students
      </div>

      <script>
        window.onload = function() {
          setTimeout(function() {
            window.print();
          }, 300);
        };
      </script>
    </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}
